[tool.black]
line-length = 100
skip-string-normalization = 1

[tool.isort]
atomic = true
line_length = 100
multi_line_output = 3
skip_gitignore = true
known_first_party = ["validphys", "eko", "n3fit", "reportengine"]
force_sort_within_sections = true
