[tool.black]
line-length = 100

[tool.isort]
atomic = true
line_length = 100
skip_gitignore = true
skip_glob = ["src/blib2to3", "tests/data", "profiling"]
known_first_party = ["validphys", "eko", "n3fit"]
force_sort_within_sections = true
